name: moodmonster
description: "We are JeongtongJIB"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #Status management
  flutter_riverpod: ^2.6.1 #상태관리 패키지
  riverpod_annotation: ^2.6.1 #riverpod
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  #DB
  shared_preferences: ^2.5.2 #tinydb
  flutter_secure_storage: ^9.2.4 #난독화 tinydb
  sqflite: ^2.4.2 #flutter SQL

  #web
  url_strategy: ^0.2.0 #링크에 샵 삭제
  seo_renderer: ^0.6.0 #seo rendering

  #etc
  flutter_screenutil: 5.9.0 #화면 사이즈 controlling
  http: ^1.3.0
  cached_network_image: ^3.4.1 #web 로딩 속도 줄이기 & tick마다 새로그리기 방지
  flutter_svg: ^2.0.17 #svg 사용하기 위함
  image_picker: ^1.1.2
  file_picker: ^9.2.1
  just_audio: ^0.9.46
  device_info_plus: ^11.3.3 #device info

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  riverpod_lint: ^2.6.5
  freezed: ^3.0.3
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/svgs/
    - assets/fonts/
    - assets/audio/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
